version: "3.9"

services:
  db:
    image: postgres:15
    container_name: esg_db
    restart: always
    environment:
      POSTGRES_DB: esgdb
      POSTGRES_USER: esguser
      POSTGRES_PASSWORD: esgpassword
    volumes:
      - esg_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi:
    build: .
    container_name: esg_fastapi
    restart: always
    command: uvicorn api_main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: esgdb
      DB_USER: esguser
      DB_PASSWORD: esgpassword
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  esg_db_data: